# docker-compose.yml
version: '3.8'

services:
  aawsa-billing-portal:
    # Build the image from the Dockerfile in the current directory
    build:
      context: .
      # During the build, we pass the local environment variables as build arguments
      # so that the Next.js app can connect to Supabase to generate static pages.
      # Make sure your .env.local file has these values.
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    image: aawsa-billing-portal-app
    container_name: aawsa_billing_portal_app_container
    
    # Forward the exposed port 3000 on the container to port 3000 on the host machine
    ports:
      - "3000:3000"
      
    # Here we define the environment variables that the application will use when it runs.
    # It's crucial that these point to your PRODUCTION Supabase instance, not the local one.
    # You should create a .env file in your project root for these values.
    env_file:
      - .env # Loads variables from a .env file (e.g., for production Supabase keys)
      
    # Restart policy: ensures the container restarts automatically if it stops
    restart: unless-stopped
